[package]
name = "aoc_2019"
version = "0.1.0"
authors = ["Karl McCarron <karl.mccarron@eggplant.io>"]

[dependencies]
itertools = "0.8.1"
permutate = "0.3.2"
lazy_static = "1.4.0"
regex = "1"
chrono = "0.4"
